#!/bin/bash

# symlink .vimrc
ln -sf ~/.dotfiles/vim/.vimrc ~/.vimrc

# symlink .bashrc
ln -sf ~/.dotfiles/shells/.zshrc ~/.zshrc

# set up commands to run after vim plugins load
mkdir -p .vim/after
ln -sf ~/.dotfiles/vim/after_plugin ~/.vim/after/plugin

# map ftplugin settings
ln -sf ~/.dotfiles/vim/ftplugin/ ~/.vim/

cd .dotfiles/brew
brew bundle install

# open apps to create their profiles if needed
open -a RStudio
open -a Karabiner-Elements
open -a iterm

echo sleeping 30 sec
sleep 30


# Specify the preferences directory of iterm2
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.dotfiles/iterm2"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# map rstudio user settings
ln -sf ~/.dotfiles/r/user-settings ~/.rstudio-desktop/monitored/user-settings/user-settings

# map rstudio key bindings
ln -sf ~/.dotfiles/r/keybindings ~/.R/rstudio

Rscript ~/.dotfiles/r/install_r_packages.R

# link up karabiner config
# This doesnt seem to persist well and gets writen over
ln -sf ~/.dotfiles/configs/karabiner.json ~/.config/karabiner/karabiner.json

# link p10k settings for zsh
ln -sf ~/.dotfiles/shells/.p10k.zsh ~/.p10k.zsh

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Set global .gitignore
git config --global core.excludesfile ~/.dotfiles/git/.gitignore
